translate_dict = {
    "adjusted_average_yield": {"en": "Adjusted Average Yield", "es": "Rendimiento Medio Ajustado", "pt": "Rendimento Médio Ajustado"},
    "adjusted_average_yield_by": {"en": "Adjusted Average Yield by", "es": "Rendimiento medio ajustado por", "pt": "Rendimento Médio Ajustado por"},
    "area": {"en": "Area", "es": "Área", "pt": "Área"},
    "average_yield": {"en": "Average Yield", "es": "Rendimiento Medio", "pt": "Rendimento Médio"},
    "choose_option": {"en": "Choose an option", "es": "Elije una opción", "pt": "Escolha uma opção"},
    "color_palette": {"en": "Color Palette", "es": "Paleta de colores", "pt": "Paleta de Cores"},
    "crop": {"en": "Crop", "es": "Cultivo", "pt": "Cultivo"},
    "download_csv": {"en": "Download CSV", "es": "Descargar CSV", "pt": "Baixar CSV"},
    "farm": {"en": "Farm", "es": "Establecimiento", "pt": "Fazenda"},
    "field": {"en": "Field", "es": "Lote", "pt": "Campo"},
    "heatmap": {"en": "Heatmap by Yield", "es": "Heatmap por rendimiento", "pt": "Heatmap por rendimento"},
    "hybrid_variety": {"en": "Hybrid / Variety", "es": "Híbrido / Variedad", "pt": "Híbrido / Variedade"},
    "language": {"en": "Language", "es": "Idioma", "pt": "Idioma"},
    "logout": {"en": "Logout", "es": "Cerrar Sesión", "pt": "Sair"},
    "point_map_by_layer_according_to": {"en": "Point Map by Layer According to", "es": "Mapa de puntos por capa según", "pt": "Mapa de Pontos por Camada Segundo"},
    "requested_by": {"en": "Requested by: ", "es": "Solicitado por: ", "pt": "Solicitado por: "},
    "season": {"en": "Season", "es": "Campaña", "pt": "Temporada"},
    "select_all": {"en": "Select all", "es": "Seleccionar todo", "pt": "Selecionar tudo"},
    "select_grouping_field": {"en": "Select a grouping field:", "es": "Seleccione un campo de agrupamiento:", "pt": "Selecione um campo de agrupamento:"},
    "select_yield_layer_warning": {"en": "You must select a yield layer to continue", "es": "Debe seleccionar una capa de rindes para continuar", "pt": "Você deve selecionar uma camada de rendimento para continuar"},
    "title": {"en": "Yield Dashboard", "es": "Tablero de Rindes", "pt": "Painel de Rendimento"},
    "weighted_yield": {"en": "Weighted Yield", "es": "Rendimiento Ponderado", "pt": "Rendimento Ponderado"},
    "weighted_yield_by": {"en": "Weighted Yield by", "es": "Rendimiento Ponderado por", "pt": "Rendimento Ponderado por"},
    "workspace": {"en": "Work Space", "es": "Espacio de Trabajo", "pt": "Espaço de Trabalho"},
    "yield_layer": {"en": "Yield Layer", "es": "Capa de Rinde", "pt": "Camada de Rendimento"},
    "yield_layers": {"en": "Yield Layers", "es": "Capas de rindes", "pt": "Camadas de Rendimento"}
}
